spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_schema
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db.migration

application:
  version: v1
